export routes = [{
    key:"why-bikes",
    path:"/why-bikes",
},{
    key:"login-page",
    path:"/login-page",
},{
    key:"about-us",
    path:"/about-us",
},{
    key:"contact-us",
    path:"/contact-us",
},{
    key:"login",
    path:"/login",
},{
    key:"sign-up",
    path:"/sign-up",
},{
    key:"home-page",
    path:"/",
},{
    key:"approach",
    path:"/approach",
}];
