export routes = [{
    key:"why-bikes",
    path:"/why-bikes",
},{
    key:"signin-page",
    path:"/signin-page",
},{
    key:"about-us",
    path:"/about-us",
},{
    key:"contact-us",
    path:"/contact-us",
},{
    key:"signin",
    path:"/signin",
},{
    key:"sign-up",
    path:"/sign-up",
},{
    key:"home-page",
    path:"/",
},{
    key:"approach",
    path:"/approach",
}];
